// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIdentity(arg1) {
  return window['go']['main']['App']['GetIdentity'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InitUser(arg1) {
  return window['go']['main']['App']['InitUser'](arg1);
}

export function IsLocked() {
  return window['go']['main']['App']['IsLocked']();
}

export function ReleaseIdentity(arg1) {
  return window['go']['main']['App']['ReleaseIdentity'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetPassword(arg1) {
  return window['go']['main']['App']['SetPassword'](arg1);
}

export function VerifyPassword(arg1) {
  return window['go']['main']['App']['VerifyPassword'](arg1);
}
