// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetIdentity(arg1:string):Promise<string>;

export function GetSettings():Promise<main.GatewaySettings>;

export function InitUser(arg1:string):Promise<string>;

export function IsLocked():Promise<boolean>;

export function ReleaseIdentity(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.GatewaySettings):Promise<void>;

export function SetPassword(arg1:string):Promise<void>;

export function VerifyPassword(arg1:string):Promise<boolean>;
